org:
  neo4j:
    migrations:
      locations-to-scan:
      packages-to-scan: com.astrum.db.migrations.neo4j
      installed-by: astrum
spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true
  neo4j:
    pool:
      metrics-enabled: true
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: ${NEO4J_PASSWORD:margin-saturn-presto-saga-slogan-8117}
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
    sun.rmi.transport.tcp: ERROR

app:
  security:
    content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:"
    oauth2:
      audience:
        - account
        - api://default
