version: '3.8'
services:
  neo4j:
    image: neo4j
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_conf:/conf:ro
      - neo4j_data:/data:rw
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_logs:/logs:rw
      - neo4j_plugins:/plugins:rw
    environment:
      # Raise memory limits
      - NEO4J_server.memory.pagecache.size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_server.memory.heap.max_size=1G
volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
  neo4j_import:
  neo4j_conf:
