server:
  port: 8080
spring:
  application:
    name: talentum
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/astrum
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
    sun.rmi.transport.tcp: ERROR